# Register extensible-type factories with the current runtime plugin loader.
# Keep legacy factory names at the extension boundary, not in core registries.
include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/RuntimeRegistrationUtil.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/UnreflectionRegistrationUtil.cmake)

function(add_extension_library key registry legacy_parent target)
    string(REGEX REPLACE "-registry$" "" parent "${legacy_parent}")
    add_library(${target} STATIC ${ARGN})
    target_link_libraries(${target} PRIVATE ${parent})
    target_include_directories(${target} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
    link_plugin_library(${parent} ${target})
    set(factory "Register${key}${registry}")
    set(declaration "${CMAKE_CURRENT_BINARY_DIR}/${target}_factory.hpp")
    file(WRITE "${declaration}" "#pragma once\n#include <${registry}Registry.hpp>\nnamespace NES::${registry}GeneratedRegistrar {\n${registry}RegistryReturnType ${factory}(${registry}RegistryArguments);\n}\n")
    target_compile_options(${target} PRIVATE "-include" "${declaration}")
    set(glue "${CMAKE_CURRENT_BINARY_DIR}/${target}_registration.cpp")
    file(WRITE "${glue}" "#include <any>\n#include <Plugins/BuiltinPlugins.hpp>\n#include \"${declaration}\"\nnamespace NES { namespace {\nvoid describe(PluginDescriptor& descriptor) {\n descriptor.entries.push_back(EntryProvision{.registryClassName = \"${registry}Registry\", .key = \"${key}\", .entry = std::any{${registry}Registry::EntryType{&${registry}GeneratedRegistrar::${factory}}}, .optional = false});\n}\nconst auto collected = [] { BuiltinPlugins::instance().addDescriber(&describe); return 0; }();\n}}\n")
    add_library(${target}_registration STATIC "${glue}")
    target_link_libraries(${target}_registration PRIVATE $<COMPILE_ONLY:${parent}>)
    add_dependencies(${target}_registration ${parent})
    target_link_libraries(${parent} INTERFACE $<LINK_LIBRARY:WHOLE_ARCHIVE,${target}_registration>)
    # Factory and deserialization are separate registrations in current main.
    if(registry STREQUAL "LogicalFunction")
        list(GET ARGN 0 source)
        get_filename_component(class ${source} NAME_WE)
        string(REGEX REPLACE "LogicalFunction$" "" stem "${class}")
        file(READ "${CMAKE_CURRENT_SOURCE_DIR}/${source}" source_text)
        string(REGEX MATCH "#include <([^>]+)>" first_include "${source_text}")
        set(header "${CMAKE_MATCH_1}")
        add_unreflection_entry(LogicalFunction ${stem} KEY ${key} HEADER "${header}")
    endif()
endfunction()
